version: "3.9"
services:
  #Django app
  user_service:
    container_name: service_logs
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    environment:
      - SECRET_KEY='django-insecure-)7xkxwb1mz%14+9ga74^k#qu^o=y)l&w#91g@=fxbksrt*6^rr'
      - DEBUG=True
      - DATABASE_URL=postgres://desarrollo:desa1234*.#rollo@db:5432/logs_db 
    depends_on:
      - db
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py migrate oauth2_provider &&
      python manage.py runserver 0.0.0.0:8001
      "
 
  
  # Database (PostgreSQL)
  db:
   image: postgres
   container_name: django_logs_postgresql
   restart: always
   environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: desarrollo
      POSTGRES_PASSWORD: desa1234*.#rollo
   ports:
    - 54323:5432
   volumes:
      - .dbdata:/var/lib/postgresql
  
  

volumes:
  .dbdata: